id: CONFIGURATION-624
description: Support Commons Configuration as PropertySource in Spring
project:
  name: Commons-configuration
  project url: https://github.com/MSR-2017/commons-configuration
issue url: https://issues.apache.org/jira/browse/CONFIGURATION-624
history start: 89428f1
history end: 9fb4ad8
test suite:
  - "TestConfigurationPropertiesFactoryBean.testAfterPropertiesSet"
  - "TestConfigurationPropertiesFactoryBean.testGetObject"
  - "TestConfigurationPropertiesFactoryBean.testMergeConfigurations"
  - "TestConfigurationPropertiesFactoryBean.testLoadResources"
  - "TestConfigurationPropertiesFactoryBean.testInitialConfiguration"
  - "TestConfigurationPropertiesFactoryBean.testSetLocationsDefensiveCopy"
  - "TestConfigurationPropertiesFactoryBean.testSetLocationsNull"
  - "TestConfigurationPropertiesFactoryBean.testGetLocationsDefensiveCopy"
  - "TestConfigurationPropertiesFactoryBean.testSetConfigurationsDefensiveCopy"
  - "TestConfigurationPropertiesFactoryBean.testGetConfigurationDefensiveCopy"
  - "TestConfigurationPropertySource.testValueInjection"
history slice:
  - "d377fbbd"
  - "fc534100"
  - "75b2d209"
  - "8fc74a9b"
  - "e4071db6"
  - "1f207424"
  - "cf9cbbda"
  - "00d9578b"
  - "3410aed6"
  - "8d34352d"
  - "447baf81"
  - "40741a9d"
  - "85eaaf74"
  - "b29dcd58"
  - "f3a8208d"
  - "1761c73c"
  - "d042d359"
  - "b1d7b38a"
  - "436ea067"
  - "edbe77e5"
  - "67407f28"
  - "bea5ca11"
  - "7344ddb4"
  - "3cc0a5da"
  - "0cb26ac6"
  - "628813c0"
  - "5544b5af"
  - "2ccca975"
  - "404f5ed2"
  - "7064987a"
  - "4b01de88"
  - "f65eeb63"
  - "19abbba0"
  - "05077ebc"
  - "e7294a6d"
  - "db9e5bea"
  - "57753e16"
  - "0e1332c0"
  - "b3c7c41b"
  - "849306df"
  - "bd09c878"
  - "dbe87b57"
  - "6485eb72"
  - "afbaa957"
  - "561ed068"
  - "982ebe93"
  - "6b70cd16"
  - "53f9e5a9"
